### ISSUE TITLE
Integrate group participants' items into the Pantry tab

### ISSUE THREAD

**Issue by henrijaeger** [WeFridge/WeFridge#44] opened 2021-12-06 21:57 UTC
When listing items under the 'Pantry' tab, items of the group participants should appear there, too.
This enables our users to manage a list of pantry items collaboratively.

**Comment by frcroth** [comment] 2021-12-06 22:19
Currently not supported by firebase security rules

**Comment by PassiDel** [comment] 2021-12-07 20:26
Duplicate of #24

**Closed** 2021-12-12 14:03 UTC
Labels: duplicate
